language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

os:
  - linux

branches:
  only:
  - master
  - develop

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - echo "deb http://us.archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y rpmlint
  - sudo ln -sf /usr/bin/python2.7 /usr/bin/python2.6
  - make deps
  - make deps-test 

script:
  - .travis/script.sh
