language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

os:
  - linux

branches:
  only:
  - master
  - develop

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

cache: apt

env:
  - SHELLCHECK_VERSION=0.7.1
  - HADOLINT_VERSION=1.17.5

before_install:
  - wget https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
  - wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-x86_64
  - tar xf shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
  - mv shellcheck-v${SHELLCHECK_VERSION} shellcheck-latest
  - echo "deb http://us.archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y rpmlint
  - sudo ln -sf /usr/bin/python2.7 /usr/bin/python2.6
  - chmod +x hadolint
  - ./shellcheck-latest/shellcheck --version
  - ./hadolint --version
  - rpmlint --version
  - make deps
  - make deps-test 

script:
  - .travis/script.sh
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck perfecto-docker'
  - ./hadolint centos6.docker
  - ./hadolint centos7.docker
